const chapters = [
    { value: 'Alabama', label: 'Alabama', logo: 'alabama', url: 'alabama' },
    { value: 'Alaska', label: 'Alaska', logo: 'alaska', url: 'alaska' },
    { value: 'Arizona', label: 'Arizona', logo: 'arizona', url: 'arizona' },
    { value: 'Arkansas', label: 'Arkansas', logo: 'arkansas', url: 'arkansas' },
    { value: 'Capital Region New York', label: 'Capital Region New York', logo: 'capital-region-new-york', url: 'capitalregionny' },
    { value: 'Central Florida', label: 'Central Florida', logo: 'central-florida', url: 'centralflorida' },
    { value: 'Central New York', label: 'Central New York', logo: 'central-new-york', url: 'centralny' },
    { value: 'Central Texas', label: 'Central Texas', logo: 'central-texas', url: 'centraltexas' },
    { value: 'Central Valley California', label: 'Central Valley California', logo: 'central-valley', url: 'centralvalley' },
    { value: 'Colorado', label: 'Colorado', logo: 'colorado', url: 'colorado' },
    { value: 'Connecticut', label: 'Connecticut', logo: 'connecticut', url: 'connecticut' },
    { value: 'Delaware', label: 'Delaware', logo: 'delaware', url: 'delaware' },
    { value: 'Eastern Pennsylvania', label: 'Eastern Pennsylvania', logo: 'eastern-pennsylvania', url: 'easternpa' },
    { value: 'Florida Panhandle', label: 'Florida Panhandle', logo: 'florida-panhandle', url: 'panhandle' },
    { value: 'Georgia', label: 'Georgia', logo: 'georgia', url: 'georgia' },
    { value: 'Greater Kansas', label: 'Greater Kansas', logo: 'greater-kansas', url: 'kansas' },
    { value: 'Greater Los Angeles and Central Coast', label: 'Greater Los Angeles and Central Coast', logo: 'greater-los-angeles-and-central-coast', url: 'la' },
    { value: 'Greater Philadelphia', label: 'Greater Philadelphia', logo: 'greater-philadelphia', url: 'philadelphia' },
    { value: 'Greater Sacramento', label: 'Greater Sacramento', logo: 'greater-sacramento', url: 'sacramento' },
    { value: 'Greater San Francisco Bay Area', label: 'Greater San Francisco Bay Area', logo: 'greater-san-francisco-bay', url: 'sfbayarea' },
    { value: 'Hawaii', label: 'Hawaii', logo: 'hawaii', url: 'hawaii' },
    { value: 'Hudson Valley/Westchester', label: 'Hudson Valley/Westchester', logo: 'hudson-valley-westchester', url: 'hvwestchester' },
    { value: 'Idaho', label: 'Idaho', logo: 'idaho', url: 'idaho' },
    { value: 'Illinois', label: 'Illinois', logo: 'illinois', url: 'illinois' },
    { value: 'Indiana', label: 'Indiana', logo: 'indiana', url: 'indiana' },
    { value: 'Inland Empire and Desert Cities', label: 'Inland Empire and Desert Cities', logo: 'inland-empire-and-desert-cities', url: 'inlandempiredc' },
    { value: 'Iowa', label: 'Iowa', logo: 'iowa', url: 'iowa' },
    { value: 'Kentucky', label: 'Kentucky', logo: 'kentucky', url: 'kentucky' },
    { value: 'Louisiana', label: 'Louisiana', logo: 'louisiana', url: 'louisiana' },
    { value: 'Maine', label: 'Maine', logo: 'maine', url: 'maine' },
    { value: 'Maryland', label: 'Maryland', logo: 'maryland', url: 'maryland' },
    { value: 'Massachusetts', label: 'Massachusetts', logo: 'massachusetts', url: 'massachusetts' },
    { value: 'Michigan', label: 'Michigan', logo: 'michigan', url: 'michigan' },
    { value: 'Minnesota', label: 'Minnesota', logo: 'minnesota', url: 'minnesota' },
    { value: 'Mississippi', label: 'Mississippi', logo: 'mississippi', url: 'mississippi' },
    { value: 'Missouri', label: 'Missouri', logo: 'missouri', url: 'missouri' },
    { value: 'Montana', label: 'Montana', logo: 'montana', url: 'montana' },
    { value: 'National Capital Area', label: 'National Capital Area', logo: 'national-capital-area', url: 'ncac' },
    { value: 'Nebraska', label: 'Nebraska', logo: 'nebraska', url: 'nebraska' },
    { value: 'Nevada', label: 'Nevada', logo: 'nevada', url: 'nevada' },
    { value: 'New Hampshire', label: 'New Hampshire', logo: 'new-hampshire', url: 'newhampshire' },
    { value: 'New Jersey', label: 'New Jersey', logo: 'new-jersey', url: 'newjersey' },
    { value: 'New Mexico', label: 'New Mexico', logo: 'new-mexico', url: 'newmexico' },
    { value: 'New York City', label: 'New York City', logo: 'new-york-city', url: 'nyc' },
    { value: 'New York Long Island', label: 'New York Long Island', logo: 'new-york-long-island', url: 'longisland' },
    { value: 'North Carolina', label: 'North Carolina', logo: 'north-carolina', url: 'northcarolina' },
    { value: 'North Dakota', label: 'North Dakota', logo: 'north-dakota', url: 'northdakota' },
    { value: 'North Florida', label: 'North Florida', logo: 'north-florida', url: 'northflorida' },
    { value: 'North Texas', label: 'North Texas', logo: 'north-texas', url: 'northtexas' },
    { value: 'Ohio', label: 'Ohio', logo: 'ohio', url: 'ohio' },
    { value: 'Oklahoma', label: 'Oklahoma', logo: 'oklahoma', url: 'oklahoma' },
    { value: 'Orange County', label: 'Orange County', logo: 'orange-county', url: 'orangecounty' },
    { value: 'Oregon', label: 'Oregon', logo: 'oregon', url: 'oregon' },
    { value: 'Rhode Island', label: 'Rhode Island', logo: 'rhode-island', url: 'rhodeisland' },
    { value: 'San Diego', label: 'San Diego', logo: 'san-diego', url: 'sandiego' },
    { value: 'South Carolina', label: 'South Carolina', logo: 'south-carolina', url: 'southcarolina' },
    { value: 'South Central New York', label: 'South Central New York', logo: 'south-central-new-york', url: 'southcentralny' },
    { value: 'South Dakota', label: 'South Dakota', logo: 'south-dakota', url: 'southdakota' },
    { value: 'Southeast Florida', label: 'Southeast Florida', logo: 'southeast-florida', url: 'southeastflorida' },
    { value: 'Southeast Texas', label: 'Southeast Texas', logo: 'southeast-texas', url: 'southeasttexas' },
    { value: 'South Texas', label: 'South Texas', logo: 'south-texas', url: 'southtexas' },
    { value: 'Southwest Florida', label: 'Southwest Florida', logo: 'southwest-florida', url: 'southwestflorida' },
    { value: 'Tampa Bay', label: 'Tampa Bay', logo: 'tampa-bay', url: 'tampa' },
    { value: 'Tennessee', label: 'Tennessee', logo: 'tennessee', url: 'tennessee' },
    { value: 'Utah', label: 'Utah', logo: 'utah', url: 'utah' },
    { value: 'Vermont', label: 'Vermont', logo: 'vermont', url: 'vermont' },
    { value: 'Virginia', label: 'Virginia', logo: 'virginia', url: 'virginia' },
    { value: 'Washington', label: 'Washington', logo: 'washington', url: 'washington' },
    { value: 'Western New York', label: 'Western New York', logo: 'western-new-york', url: 'westernny' },
    { value: 'Western Pennsylvania', label: 'Western Pennsylvania', logo: 'western-pennsylvania', url: 'westernpa' },
    { value: 'West Virginia', label: 'West Virginia', logo: 'west-virginia', url: 'westvirginia' },
    { value: 'Wisconsin', label: 'Wisconsin', logo: 'wisconsin', url: 'wisconsin' },
    { value: 'Wyoming', label: 'Wyoming', logo: 'wyoming', url: 'wyoming' },
]

export default chapters
